### PR TITLE
Feature/jc queue job query restriction

### PR DESCRIPTION
**Pull request by mxab**
Adds a additional restriction to the jobs that will be run by the node.

### CODE REVIEW

**Comment by rhyslbw** [comment]
I've thought about this more and we actually need to put the primary logic in the worker function like your first concept as the observing query is only triggering the worker to request a job. I'm also now thinking we provide an option for the behaviour rather then a lower level hook into the query.

**Comment by mxab** [comment]
Ok, but I think some query restriction might still be good in terms of performance, otherwise the job manager might iterate over a lot of tasks that it is responsible for

**Comment by rhyslbw** [comment]
Yes that's what I was meaning. Ok so let's replace `jobQueryRestriction` with `localJobsOnly` (unless you can think of a more expressive name), and then rework the solution to handle this use case directly.

**Comment by rhyslbw** [comment]
…actually maybe we should just auto detect FileSystem as the TempStore to apply this filter in the queries? Can you see any issues with that?

**Comment by mxab** [comment]
hmm maybe if you run it with meteor cluster and you have actually a FSFileSystem that is shared between the processes you might want to not use the ```localJobsOnly``` and if we have the local jobs only version autodetection we need to introduce a fixed node id somehow or at least enforce the configuration on startup

**Comment by rhyslbw** [comment]
In the case of using meteorhacks:cluster, the instances would all have the same id if set using an ENV variable. I'll have a think…

**Pull request closed without merging**
